title: Kaiona Apio # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Man of Mystery
  <br><br>
  oooo mystery
  <br><br>
  <a href="www.linkedin.com/in/kaionaapio">View My LinkedIn Profile</a> 
  
theme: minimal-mistakes-jekyll
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
